# Generated by Django 3.0.4 on 2020-03-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=100)),
                ('submitter', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField()),
                ('petSpecies', models.CharField(max_length=30)),
                ('petBreed', models.CharField(blank=True, max_length=30)),
                ('petDescription', models.TextField()),
                ('petSex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('petAge', models.IntegerField(null=True)),
                ('petVaccinations', models.ManyToManyField(blank=True, to='petapp.Vaccine')),
            ],
        ),
    ]
