# Generated by Django 3.0.4 on 2020-03-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name_plural': 'pets'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name_plural': 'vaccines'},
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
        migrations.AlterModelTable(
            name='vaccine',
            table='vaccine',
        ),
    ]
