# Generated by Django 3.0.4 on 2020-03-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_auto_20200323_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='petVaccinations',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
